#
# Sambaza H265
# An RTSP server for H265 video frames
#
# Sambaza H265 is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 2.1 of the License, or
# (at your option) any later version.
#
# Sambaza H265 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Sambaza H265.  If not, see <http://www.gnu.org/licenses/>.
#
# This fork is based on commit [3a46d6c](https://github.com/Auterion/sambaza/commit/3a46d6cca5b7375b3a58b77fcf9a42e468479c55) of Sambaza
# - Changes to this file are that nearly all the build targets, and tasks
# have been removed except for building arm64. Since building via this script
# is our primary mechanism to build we just execute a build on every push.
#
# Modified Library info:
# - Modification Author: [Adam Ward](https://github.com/AdamWardVGP)
#
# Original library info:
# - Base Library: Sambaza
# - Original Author: [Jonas Vautherin](https://git.sr.ht/~jonasvautherin/)
# - Original License: GNU Lesser General Public License
# - Original License Version: v2.1
# - Original License URL: https://git.sr.ht/~jonasvautherin/sambaza/tree/main/item/LICENSE
#
name: Build and Test

on: [push]

jobs:
  android-c:
    name: libsambaza.so (${{ matrix.name }})
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: android-arm64
            arch: arm64-v8a
    steps:
      - uses: actions/checkout@v3
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: src/build/dependencies/${{ matrix.name }}/install
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./src/dependencies/**') }}
      - name: cross-compile and install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./dockcross-${{ matrix.name }} cmake -DCMAKE_PREFIX_PATH=/work/build/dependencies/${{ matrix.name }}/install -DCMAKE_INSTALL_PREFIX=build/dependencies/${{ matrix.name }}/install -Bbuild/dependencies/android -Sdependencies
          ./dockcross-${{ matrix.name }} cmake --build build/dependencies/android
      - name: cross-compile main project
        run: |
          ./dockcross-${{ matrix.name }} cmake -DCMAKE_PREFIX_PATH=/work/build/dependencies/${{ matrix.name }}/install -Bbuild/main -Smain
          ./dockcross-${{ matrix.name }} cmake --build build/main
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: src/build/main/libsambaza.so

  android-aar:
    name: android
    needs: android-c
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: arm64-v8a
          path: android/src/main/jniLibs/arm64-v8a/
      - name: build
        run: ./gradlew assembleDebug
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: "sambaza-${{ github.head_ref }}.aar"
          path: ./android/build/outputs/aar/sambaza-debug.aar
          retention-days: 14
  android_test:
    name: Run Kotlin tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: android
        run: ./gradlew test
