name: Build and Test

on: [push]

jobs:
  android-c:
    name: libsambaza.so (${{ matrix.name }})
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: src
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: android-arm64
            arch: arm64-v8a
    steps:
      - uses: actions/checkout@v3
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: src/build/dependencies/${{ matrix.name }}/install
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./src/dependencies/**') }}
      - name: cross-compile and install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          ./dockcross-${{ matrix.name }} cmake -DCMAKE_PREFIX_PATH=/work/build/dependencies/${{ matrix.name }}/install -DCMAKE_INSTALL_PREFIX=build/dependencies/${{ matrix.name }}/install -Bbuild/dependencies/android -Sdependencies
          ./dockcross-${{ matrix.name }} cmake --build build/dependencies/android
      - name: cross-compile main project
        run: |
          ./dockcross-${{ matrix.name }} cmake -DCMAKE_PREFIX_PATH=/work/build/dependencies/${{ matrix.name }}/install -Bbuild/main -Smain
          ./dockcross-${{ matrix.name }} cmake --build build/main
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: src/build/main/libsambaza.so

  android-aar:
    name: android
    needs: android-c
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: arm64-v8a
          path: android/src/main/jniLibs/arm64-v8a/
      - name: build
        run: ./gradlew assembleDebug
      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: "sambaza.aar"
          path: ./android/build/outputs/aar/sambaza-debug.aar
          retention-days: 14
  android_test:
    name: Run Kotlin tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: android
        run: ./gradlew test
